name: 'CoffeeTeX'
version: 0.0.1
description: >
  LaTeX Editor
#author: Kasper Peulen kasperpeulen@gmail.com
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
